### ISSUE TITLE
本主题非常不错，加油

### ISSUE THREAD

**Issue by huangjinbo** [85Ryan/TypeNow#1]
本主题非常不错，已启用，本人有点强迫症，所以自已使用时做了一些微改：
文章宽度与博客名字、菜单栏对于对齐。
菜单栏上的右边与文章对齐，哈哈哈。加油。
如果可以上加返回顶部按钮就好了。

**Comment by 85Ryan** [comment]
多谢喜欢！
菜单栏左边延伸了一段距离是为了使之与正文中的段落符号更协调。
菜单栏右边图标菜单放在正文 wrap 外面，是想给菜单栏更多空间，可以避免因菜单太多，导致菜单栏空间不足的状况。
个人理解不同，您可以根据您的喜好自由修改！看了您的网站，建议您再添加几行 CSS 以调整向下箭头隐藏时登录和搜索图标的位置。
